### PR TITLE
Arrays of entity type.

### PR DESCRIPTION
**Pull request by endersoncosta**
Implementation of the entity type validation on arrays. 

Issue: #17

### CODE REVIEW

**Comment by dalssoft** [comment]
It's has been very hard to understand this diff, although doesn't look like it changed that much. Is it because of some lint? Could you check it?

It looks like a good commit though

**Comment by endersoncosta** [comment]
Yes, I made this PR without lint fix and insufficient tests, I will made these changes today... Thanks!!

**Comment by endersoncosta** [comment]
I used the **_lint_** of the project, but the diff are still complex...

**Comment by dalssoft** [comment]
is this array validation also valid for Scalar types (String, Number, etc)?

**Comment by endersoncosta** [comment]
No, just with Entity ... But I will implement this, as soon as possible... In this moment the code is indeed incomplete...

**Comment by endersoncosta** [comment]
I found a problem with the metadata. When I pass several fields with typed array, the prototypes somehow are merged, then the comparison of the type aways is wrong...

**Comment by endersoncosta** [comment]
Now, the list accept Scalar types and Gotu Entities as well...

**Comment by dalssoft** [comment]
@endersoncosta could you fix the CI errors?

**Comment by endersoncosta** [comment]
Done!

**Pull request merged**
