### PR TITLE
code docs

### PR DESCRIPTION
**Pull request by italojs**
## Problem

all herbs repository is not fully documented or many delivered features isn't well documented. Another problem is a BIG readme that makes it hard to find/search by a specific feature description.

## Proposed Changes
 This PR proposes to use the [JSdocs](https://github.com/jsdoc/jsdoc) to auto-generate the documentations using the own code.

This is the first documentation version, we can discuss more the structure, themes, content, patterns, and more in the future.

Today I'm generating an HTML in docs folder and using the [brainTree](https://cancerberosgx.github.io/jsdoc-templates-demo/demo/braintree-jsdoc-template/Environment.html) theme, but the JSDocs permit use markdown and choose so many pthers theme, here we have an little [themes list](https://cancerberosgx.github.io/jsdoc-templates-demo/demo/), but if you search in the google o by `JSDocs themes` you can find many other options

### Check the doc
You can check the published version doc here https://italojs.github.io/gotu/
### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by italojs** [comment]
after got a talk with @dalssoft and @jhomarolo  I just removed the augenerating the docs feature and mantain the code docuementation because the IDEs/text Editor like VScode can read it like this.

**Comment by jhomarolo** [comment]
Does this PR have an initial issue linked to it?

**Comment by italojs** [comment]
No, because this PR was created after a private discussion about Vortx's OKR. After PR was opened, we discussed about low-level documentation or high-level documentation and we decided the low-level doc was not necessary right now, so I just removed the JS Docs in this PR

**Comment by jhomarolo** [comment]
So does it make sense to continue with this PR?

In my view, having documentation like this is very nice, but I don't know if it makes sense to have something like this, since the maintainability of the library would increase considerably, in addition to the fact that we are already working on external documentation.

**Comment by italojs** [comment]
it's already done and it's just documentation so I believed it can continue

**Pull request closed without merging**
